{% set name = "python-fitparse" %}
{% set version = "1.2.0" %}
{% set sha256 = "97e524e48d661357d5e4a1daab94400fbb8f98d40b5bd9ae4ae452a36b26a81d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/dtcooper/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fitparse

about:
  home: http://github.com/dtcooper/python-fitparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library to parse ANT/Garmin .FIT files

  description: |
    Python library to parse ANT/Garmin .FIT files
  doc_url: http://pythonhosted.org/fitparse/
  dev_url: https://github.com/dtcooper/python-fitparse

extra:
  recipe-maintainers:
    - glemaitre
