travis:
  secure:
    BINSTAR_TOKEN: WjmhJRwylY1q9wUosP6GcrHYvLcLu8wjNwyKNEN56aObI4UHs4sxqNFVzZ+utacY6lddMwUBOIJEgQk201J7tELvAVqtOAMGjp8scIG7qimqZkOdihdfi/yh35ORCsAsGNUHgiiTIW1Nl8xEWBMIQCPccvpyfX2XHUGDJ/x7wqEAcgrTowEFk/FEyxBKNNx+bowTycqx8PWD3wJDWNTYJ6Ri90c7y0Yy+IYfc57wY7nf1wzLNX2IJmaib1mWLMRaieC+N0U6H6+528dd/9rMARla7L8EdZYrSYy4BvP9Fn7HJgoET2HjWxOb215jP/xwfkAuRl1UuTAgRq/B5mOqkufjdpi/jq2CvnMR2AZ8N+MveloxMPrMb+x7tUfJIIO+Zjav6MGJYOx8Atj0dpMC6b/mp5K/t25Rqa7ZKtuIc5R2q9f97e+OqLXuYXID35MZbngO1WDuZJyyLzMAeT/wFnlTjF2Pm7g71LEV9Ch2Q83eimP6BWHTpnnsCNs6oLScwgI1QuZS2+yR2nllEShdX2ru5fwywOLkIjXlxbB52Ew+p/+kwavUsQahyLqrNOwTTZchk3ARrrzLdvQyDOHURgWCvyKjxKXpntcOfOKHKEp4gTgMsv9O9IWnJqN18DKxb/nzKLIHjyBTJGj9b31TsuNjIhJltktvv4R9boMwC+I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
