travis:
  secure:
    BINSTAR_TOKEN: rJA01dr4eifN2SuP5mnfXfxioJLrcYdS+qmvaczgOuXIejOygkELdi+iLDQ0egEep1z2dARM/lNhZD+n28WlHG3oDOpZcSSytFoSn29DCngR5X3B/Ao45BFqzfxYcLkExDouwFRMXhG8PAQnsrJWPGa6/UHZW4KeP73evmMgPnLhZ46pQ0Fomp3DtBQHPKDlO/bi3jRjSwBHMEvZOVAjJCR9rlOIyhE2sczVX5GrJHTIq+eoJFpXPZQj02SejmuYao7XV7rUKm62SGoprDx0vTXBwDQ4GjF4nefDvbf8RBjAGlJENOURdmLQ3tJA7WZolE9FW+IU6ux0NBqTmYmz5i5QkkW2YBOt/Jj/K822ZTZskjIRHHqohtEMtImXLDJq7f0Pvms+jIbXNjlY64ovL2/IFlWwQromUoR4Dp+L41GuKkUtuIDW1F0vM+S8KisE4amweHs540IfDM0hywVANoGu9FUqlM3F1dqXD0VAv1L3A+5r+aD5iOSetGhdF3RGH0XH3ROMDKFigEiADIyU9XYiAIi9wUUY/apxHkpojgtwTpBYVySDT1haJ1tYshb5qDrqhdR5+NZyygwb3T/GYgBKFFUauPFyOBWIIHW5Xr2YzCmRdSdJ8r2+GdMmbmqbWTmM50zyVXuD78m4QfbY5pCn+F9WaR+7VGQdNCP+JkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
